export const MENU_CLICKED = "MENU_CLICKED";

export const RECEIVE_SERVICES = "RECEIVE_SERVICES";
export const SERVICE_CLICKED = "SERVICE_CLICKED";
export const SERVICE_RESERVATION_SAVED = "SERVICE_RESERVATION_SAVED";
export const SERVICE_RESERVATIN_CANCELLED = "SERVICE_RESERVATIN_CANCELLED";

export const RECEIVE_BOOKED_SERVICES = "RECEIVE_BOOKED_SERVICES";
export const SERVICE_BOOKED = "SERVICE_BOOKED";
